[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"
default-run = "day-01"

[[bin]]
name = "day-01"
path = "src/day-01/main.rs"

[[bin]]
name = "day-02"
path = "src/day-02/main.rs"

[dependencies]
